name: yandex_music_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  http: ^0.13.3
  xml: ^5.1.2

dev_dependencies:
  flutter_lints: ^1.0.4
  lints: ^1.0.0
  test: ^1.16.0
